name: multiply_me
description: Test

publish_to: 'none' 

version: 1.0.0+4

environment:
  sdk: ">=2.16.0-21.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.8
  duration: ^3.0.8
  google_fonts: ^4.0.3
  font_awesome_flutter: ^10.4.0
  url_launcher: ^6.1.10
  flutter_markdown: ^0.6.14
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0 

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/imprint.md
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Black.ttf
        - asset: fonts/Roboto-BlackItalic.ttf
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-BoldItalic.ttf
        - asset: fonts/Roboto-Italic.ttf
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-LightItalic.ttf
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-MediumItalic.ttf
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Thin.ttf
        - asset: fonts/Roboto-ThinItalic.ttf
